on:
  push:
    workflow_dispatch:

name: Publish VS Code Extension to Microsoft Marketplace and Open VSX
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd k-vscode
      - run: npm ci
      - name: Publish extension to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishVSMarketplace
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      - name: Publish extension to Open VSX
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.publishVSMarketplace.outputs.vsixPath }}
          packagePath: ''
